/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaptacaoAereaRouteImport } from './routes/captacao-aerea'
import { Route as IndexRouteImport } from './routes/index'

const CaptacaoAereaRoute = CaptacaoAereaRouteImport.update({
  id: '/captacao-aerea',
  path: '/captacao-aerea',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captacao-aerea': typeof CaptacaoAereaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captacao-aerea': typeof CaptacaoAereaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captacao-aerea': typeof CaptacaoAereaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/captacao-aerea'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/captacao-aerea'
  id: '__root__' | '/' | '/captacao-aerea'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptacaoAereaRoute: typeof CaptacaoAereaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/captacao-aerea': {
      id: '/captacao-aerea'
      path: '/captacao-aerea'
      fullPath: '/captacao-aerea'
      preLoaderRoute: typeof CaptacaoAereaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptacaoAereaRoute: CaptacaoAereaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
