/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaIndexRouteImport } from './routes/loja.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LojaCarrinhoRouteImport } from './routes/loja.carrinho'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as LojaProdutoSlugRouteImport } from './routes/loja.produto.$slug'

const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LojaCarrinhoRoute = LojaCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => LojaRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const LojaProdutoSlugRoute = LojaProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => LojaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/loja': typeof LojaRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/admin/': typeof AdminIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/products': typeof AdminProductsRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/admin': typeof AdminIndexRoute
  '/loja': typeof LojaIndexRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/loja': typeof LojaRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/admin/': typeof AdminIndexRoute
  '/loja/': typeof LojaIndexRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/loja'
    | '/admin/products'
    | '/loja/carrinho'
    | '/admin/'
    | '/loja/'
    | '/loja/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/products'
    | '/loja/carrinho'
    | '/admin'
    | '/loja'
    | '/loja/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/loja'
    | '/admin/products'
    | '/loja/carrinho'
    | '/admin/'
    | '/loja/'
    | '/loja/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LojaRoute: typeof LojaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof LojaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/carrinho': {
      id: '/loja/carrinho'
      path: '/carrinho'
      fullPath: '/loja/carrinho'
      preLoaderRoute: typeof LojaCarrinhoRouteImport
      parentRoute: typeof LojaRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/produto/$slug': {
      id: '/loja/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/loja/produto/$slug'
      preLoaderRoute: typeof LojaProdutoSlugRouteImport
      parentRoute: typeof LojaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LojaRouteChildren {
  LojaCarrinhoRoute: typeof LojaCarrinhoRoute
  LojaIndexRoute: typeof LojaIndexRoute
  LojaProdutoSlugRoute: typeof LojaProdutoSlugRoute
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaCarrinhoRoute: LojaCarrinhoRoute,
  LojaIndexRoute: LojaIndexRoute,
  LojaProdutoSlugRoute: LojaProdutoSlugRoute,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LojaRoute: LojaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
